### PR TITLE
feat: expose default context metadata properties

### PR DESCRIPTION
**Pull request by marcos-abreu**
This PR exposes the context default metadata properties as it is defined on Cloudinary.

This would give the ability to get both `alt` and `caption` properties when they are available for an image.

### CODE REVIEW

**Comment by nkeat12** [comment]
Possible this will get merged?

**Comment by Hecsall** [comment]
I think that retrieving metadata such as alt text for a CMS should be a must, let me bump this, hoping this gets merged 🤞

**Comment by JamesSingleton** [comment]
@snorrees has this been added to the v3 branch? I added some metadata to an image but it doesn't seem to be coming through. I even removed that image from Sanity and re-added it to see if it would be picked up but nothing.

**Comment by frodeste** [comment]
> @snorrees has this been added to the v3 branch? I added some metadata to an image but it doesn't seem to be coming through. I even removed that image from Sanity and re-added it to see if it would be picked up but nothing.

Was this added to v3?

**Pull request merged**
